name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Docker images
        run: |
          docker build -t p10-backend ./back
          docker build -t p10-frontend ./front

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker images
        run: |
          docker tag p10-backend ${{ secrets.DOCKERHUB_USERNAME }}/p10-backend:latest
          docker tag p10-frontend ${{ secrets.DOCKERHUB_USERNAME }}/p10-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p10-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p10-frontend:latest
