name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Build Docker images
        run: |
          docker build -t bobapp-backend ./back
          docker build -t bobapp-frontend ./front

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker tag bobapp-backend ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest
          docker tag bobapp-frontend ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest
