name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Analyse SonarCloud + Tests (Frontend + Backend)
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install backend & run tests
        working-directory: ./back
        run: mvn clean verify

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./front
        run: npm ci

      - name: Run frontend tests with coverage
        working-directory: ./front
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      - name: SonarCloud Scan - Projet global
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=edouard06_P10
            -Dsonar.organization=edouard06
            -Dsonar.sources=front/src/app,back/src/main
            -Dsonar.tests=front/src,back/src/test
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=front/coverage/lcov.info
            -Dsonar.exclusions=**/*.spec.ts,**/node_modules/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
