name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-build-test:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run Tests
        working-directory: front
        run: npm run test -- --browsers=ChromeHeadless --watch=false --code-coverage


