name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-build-test:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run Tests
        working-directory: front
        run: npm run test -- --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: front/coverage/bobapp/cobertura-coverage.xml
          badge: true
          format: markdown
          indicators: true
          output: both

      - name: Print Coverage Summary
        run: cat code-coverage-results
